slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames
    map_frame: map
    base_frame: base_link
    odom_frame: base_link         # <-- no external odom, so tie it to base

    provide_odom_frame: false     # slam_toolbox won't create a fake odom->base_link
    use_scan_matching: true
    use_scan_barycenter: true

    # Topic
    scan_topic: /scan

    # General tuning-ish defaults that usually work OK to start
    resolution: 0.05              # 5cm map resolution
    max_laser_range: 8.0          # slightly > your LiDAR real range
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    transform_publish_period: 0.05
    mode: "mapping"               # online mapping mode
